# Generated by Django 4.1.7 on 2023-03-17 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavour', models.CharField(max_length=30)),
                ('size', models.FloatField()),
                ('isVegan', models.BooleanField(default=False)),
                ('isGlutenFree', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IceCreamApp.store')),
            ],
        ),
    ]
