# Generated by Django 4.1.7 on 2023-03-20 10:36

import IceCreamApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IceCreamApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tub",
            name="size",
            field=models.FloatField(validators=[IceCreamApp.models.validate_interval]),
        ),
    ]
